<?php

/* @var $this yii\web\View */

$this->title = 'Словари и глоссарии';
$this->params['breadcrumbs'][] = $this->title;
//echo "<pre>".print_r($users, true)."</pre>";
?>

<div class="row">
    <div class="col-md-9 container-fluid">
        <div class="card-box">
            <div class="row">
                <div class="col-12">
                    <div style="padding: 20px;">
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center">&nbsp;&nbsp;</p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><span style="FONT-SIZE: 12px"><span style="FONT-SIZE: 14px"><span style="COLOR: #000000"><span style="FONT-SIZE: 12px"><span style="LETTER-SPACING: 0.1pt"><o:p><span style="COLOR: #000000"><b style="mso-bidi-font-weight: normal"><span style="FONT-SIZE: 12px"><span style="FONT-SIZE: 14px"><a name="1"></a></span></span></b></span></o:p></span></span></span>А</span><o:p></o:p></span></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><span style="FONT-SIZE: 12px"><o:p></o:p></span></b></p><span style="FONT-SIZE: 12px">
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Акарициды</b> – химические средства для борьбы с растительноядными клещами.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Афициды</b> - химические средства для борьбы с тлями.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.05pt"><span style="FONT-SIZE: 14px"><span style="COLOR: #000000"><span style="FONT-SIZE: 12px"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.05pt"><a name="2"></a></span></b></span></span>Б</span><o:p></o:p></span></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.05pt"><o:p></o:p></span></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Бактерициды</b> - химические средства для борьбы с бактериями и бактериальными болез&shy;нями.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Безотвальная обработка</b> — глубокое рыхление почвы без обо&shy;рачивания ее слоев.<o:p></o:p></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Бессменный посев</span></b><span style="LETTER-SPACING: 0.1pt"> – культура в течение многих лет возделываемая на одном и том же поле.<o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Бороздование почвы</span></b><span style="LETTER-SPACING: 0.1pt"> – нарезка борозд на поверхности почвы. <o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Боронование</b> — прием обработки почвы боронами, обеспечивающий ее рыхление, перемешивание и выравнивание по&shy;верхности почвы с уничтожением проростков и всходов сорняков.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><span style="FONT-SIZE: 14px"><a name="3"></a>В</span><o:p></o:p></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><o:p></o:p></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Влагоемкость</span></b><span style="LETTER-SPACING: 0.1pt"> — это способность почвы поглощать и удерживать определенное ко&shy;личество воды.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Влажность почвы</span></b><span style="LETTER-SPACING: 0.1pt"> –<span style="mso-spacerun: yes">&nbsp; </span>общее количе&shy;ство воды, содержащееся в почве. </span><o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Влажность семян</span></b><span style="LETTER-SPACING: 0.1pt"> – содержание влаги в семенах, выраженное в процентах к массе.</span><o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Водоиспаряющая способность</span></b><span style="LETTER-SPACING: 0.1pt"> – способность почвы отдавать влагу в атмосферу.<span style="mso-spacerun: yes">&nbsp; </span>Зависит от температуры почвы и воздуха, относительной влажности воздуха, наличия ветра, цвета почвы, грансостава, структуры почвы.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Водоподъемная способность,</span></b><span style="LETTER-SPACING: 0.1pt"> или <b style="mso-bidi-font-weight: normal">капиллярность</b>, — свойство почвы как пористого тела вызывать капиллярный подъем влаги из нижних горизонтов в верхние.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Водопроницаемость </span></b><span style="LETTER-SPACING: 0.1pt">— способность почвы впитывать и пропус&shy;кать через себя воду из верхних слоев в нижние.<o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Водоудерживающая способность</span></b><span style="LETTER-SPACING: 0.1pt"> – свойство почвы удерживать воду. <o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Воздухоемкостъ</span></b><span style="LETTER-SPACING: 0.1pt"> — способность почвы содержать в себе определенное количество воздуха.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Воздухопроницаемость </span></b><span style="LETTER-SPACING: 0.1pt">— свойство почвы пропускать через себя воздух.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Вспашка</b> – прием обработки почвы, который обеспечивает оборачивание, частичное перемеши&shy;вание, рыхление и крошение обрабатываемого слоя, а также подрезание сорняков, заделку удобрений и растительных ос&shy;татков.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Всхожесть семян</b> – способность семян давать нормально развитые проростки за определенный срок проращивания. Различают лабораторную и полевую всхожесть семян.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Выравнивание почвы</b> – технологическая операция, обеспечивающая уменьшение размеров неровностей поверхности почвы.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Вспушенность почвы</b> – увеличение объема почвы.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><span style="FONT-SIZE: 14px"><a name="4"></a>Г</span><o:p></o:p></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><o:p></o:p></b></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><span class="FontStyle44"><b style="mso-bidi-font-weight: normal"><span style="FONT-STYLE: normal; mso-bidi-font-style: italic">Гербициды</span></b></span><span class="FontStyle44"><em> </em></span><span class="FontStyle33">— это химические вещества, применяемые для унич&shy;тожения проростков и всходов сорняков или другой нежелатель&shy;ной растительности в посевах сельскохозяйственных культур, плодовых и ягодных насаждениях, на пастбищах и других угодьях.<o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Гипсование</b> — химическая мелиорация с помощью гипса (CaSO<sub>4</sub>-2H<sub>2</sub>O) почв, имеющих высокую долю натрия и щелочную реакцию.<o:p></o:p></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Глубина обработки почвы </span></b><span style="LETTER-SPACING: 0.1pt">– расстояние от поверхности необработанного поля до уровня заглубления в почву органов машин и орудий.<o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Глубокая обработка почвы</span></b><span style="LETTER-SPACING: 0.1pt"> – обработка почвы на глубину более <st1:metricconverter w:st="on" productid="24 см">24 см</st1:metricconverter>.<o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Глыбистость поверхности пашни</span></b><span style="LETTER-SPACING: 0.1pt"> – показатель качества обработки почвы, выражающий процентное отношение суммарной площади глыб на участке ко всей ее площади.<o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Гранулометрический состав</span></b><span style="LETTER-SPACING: 0.1pt"> — относительное (в процентах) со&shy;держание в почвообразующей породе или почве частиц различных размеров. Различают следующие разновидности почв по грануло&shy;метрическому составу: песчаные, супесчаные, легкосуглинистые, среднесуглинистые, тяжелосуглинистые и глинистые (последние подразделяются на легкую, среднюю и тяжелую глину).<o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Гребневание</span></b><span style="LETTER-SPACING: 0.1pt"> – прием обработки почвы, обеспечивающий создание гребней на ее поверхности.<o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Гребнистая вспашка</span></b><span style="LETTER-SPACING: 0.1pt"> – вспашка с образованием гребней на поверхности поля.<o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Гребнистость пашни</span></b><span style="LETTER-SPACING: 0.1pt"> – показатель качества обработки почвы, характеризующий выравненность поверхности пашни.<o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Грядкование почвы</span></b><span style="LETTER-SPACING: 0.1pt"> – создание грядок на поверхности поля.<o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Гумусовый, или гумусово-аккумулятивный, горизонт – </span></b><span style="LETTER-SPACING: 0.1pt"><span style="mso-spacerun: yes">&nbsp;</span>об&shy;разуется в верхней части профиля и отличается максимальным содержанием гумуса и питательных веществ.<o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Гумус</span></b><span style="LETTER-SPACING: 0.1pt">—часть органического вещества почвы, представленная совокупностью специфических и неспецифических органических веществ почвы, за исключением соединений, входящих в состав живых организмов и их остатков.<o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><span style="LETTER-SPACING: 0.1pt"><o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><span style="LETTER-SPACING: 0.1pt"><b><span style="FONT-SIZE: 14px"><a name="5"></a>Д</span></b><o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><span style="LETTER-SPACING: 0.1pt"><o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Двухъярусная вспашка</span></b><span style="LETTER-SPACING: 0.1pt"> – обработка почвы, обеспечивающая взаимное перемещение двух слоев или горизонтов, их крошение и рыхление.<o:p></o:p></span></p>
    <p class="Style12" style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 0cm; LINE-HEIGHT: normal; mso-pagination: widow-orphan"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Дернина</span></b><span style="LETTER-SPACING: 0.1pt"> – верхний горизонт почвы, формирующийся под травянистой растительностью (особенно луговой), густо перепле&shy;тенный корнями растений.</span><span class="FontStyle44"><b style="mso-bidi-font-weight: normal"><span style="FONT-STYLE: normal; mso-bidi-font-style: italic"> <o:p></o:p></span></b></span></p>
    <p class="Style12" style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 0cm; LINE-HEIGHT: normal; mso-pagination: widow-orphan"><span class="FontStyle44"><b style="mso-bidi-font-weight: normal"><span style="FONT-STYLE: normal; mso-bidi-font-style: italic">Десиканты</span></b></span><span class="FontStyle44" style="FONT-STYLE: normal; mso-bidi-font-style: italic"> </span><span class="FontStyle33"><i style="mso-bidi-font-style: normal">— </i></span><span class="FontStyle33">химические препараты из группы пестицидов, вызывающие обезвоживание (подсушивание) тканей растений, что ускоряет их созревание и облегчает уборку.<o:p></o:p></span></p>
    <p class="Style12" style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 0cm; LINE-HEIGHT: normal; mso-pagination: widow-orphan"><span class="FontStyle44"><b style="mso-bidi-font-weight: normal"><span style="FONT-STYLE: normal; mso-bidi-font-style: italic">Дефолианты</span></b></span><span class="FontStyle44" style="FONT-STYLE: normal; mso-bidi-font-style: italic"> </span><span class="FontStyle33"><i style="mso-bidi-font-style: normal">— </i></span><span class="FontStyle33">химические препараты из группы пестицидов, применяемые для удаления (опадения) листьев с целью облегче&shy;ния уборки урожая (в основном хлопчатника), а также для удале&shy;ния листьев перед пересадкой плодовых деревьев и кустарников.<o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Дискование</span></b><span style="LETTER-SPACING: 0.1pt"> – прием обработки почвы дисковыми орудиями, обеспечивающий крошение, рыхление, перемешивание, частичное оборачивание почвы, разрезание дернины и уничтожение сорняков.<o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Дражирование – </b>способ предпосевной подготовки семян, используется для мелкосемянных культур с целью равномерного размещения их при посеве рядовыми сеялками.<o:p></o:p></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><span style="LETTER-SPACING: 0.1pt"><span style="FONT-SIZE: 14px"><b><a name="6"></a>З</b></span><o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><span style="LETTER-SPACING: 0.1pt"><o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="mso-bidi-font-size: 12.0pt">Занятым</span></b><span style="mso-bidi-font-size: 12.0pt"> называют пар, в течение некоторого периода заня&shy;тый культурными растениями, а в остальное время подверга&shy;ющийся обработке.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Засорителями</span></b><span style="LETTER-SPACING: 0.1pt"> — культурные растения, произрастающие в посевах сельскохозяй&shy;ственных культур другого вида или сорта.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Зеленые удобрения</b> <b style="mso-bidi-font-weight: normal">(сидераты)</b>— свежая растительная масса, которую запа&shy;хивают в почву для обогащения ее и последующих культур орга&shy;ническим веществом и элементами питания.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Зооциды или родентициды</b> - для борьбы с грызунами.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify">Зяблевая обработка почвы – основная обработка почвы, выполняемая в летне-осенний период под посев или посадку с.-х. культур в следующем году.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><span style="FONT-SIZE: 14px"><a name="7"></a>И</span><o:p></o:p></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><o:p></o:p></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Известкование</b> – метод химической мелиорации, который применяют для снижения повышенной кислотности почв.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Инсектициды</b> (от латинского insectum - насекомое и caedo - убиваю) - химические препараты из группы пестицидов для уничтожения насекомых - вредителей растений, их яиц (овициды) и личинок (ларвициды).<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Инсектоакарициды</b> – химические средства для борьбы одновременно с вредными насе&shy;комыми и клещами<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Инкрустация</b> – технологический процесс, посредством которого на поверхность семян наносится жидкий состав на основе водного раствора пленкообразователя, создающего защитную среду, в который введены вещества стимулирующие рост и развитие растений.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><span style="FONT-SIZE: 14px"><a name="8"></a>К</span><o:p></o:p></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><o:p></o:p></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Капельный полив</b> - метод полива непосредственно в корневую область растения, по управляемой норме, которая позволяет получить максимальные результаты и минимально использовать воду, удобрения и другие ресурсы.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Качество обработки почвы – </b>совокупность показателей, характеризующих соответствие состояния почвы после ее обработки агротехническим требованиям.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Калибрование семян</b> – разделение семян на фракции, выровненные по физическим параметрам: длине, толщине, ширине, диаметру. Использование калиброванных семян обеспечивает высокую точность посева.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Кондиционная влажность семян</b> – оптимальная для закладки их на хранение. В зависимости от культуры находится в пределах 9-15%.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Кондиционные семена</b> – семена, посевные качества которых соответствуют государственному стандарту.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Контурная обработка почвы</b> – обработка почвы сложных склонов в направлении, близком к горизонталям местности.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Кротование</b><span style="mso-spacerun: yes">&nbsp; </span>- прием обработки почвы, обеспечивающий образование в ней дрен-кротовин.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Крошение почвы</b> – технологическая операция при обработке почвы, обеспечивающая уменьшение размеров почвенных структурных отдельностей.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Культивация</b> — прием сплошной или междурядной обработки почвы куль&shy;тиваторами для рыхления, перемешивания почвы и подрезания сорняков. Глубина обработки от 5 — 6 до 10—12 см.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Культурная вспашка</b> – вспашка плугом с предплужником.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><span style="FONT-SIZE: 14px"><a name="9"></a>Л</span><o:p></o:p></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><o:p></o:p></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Лиманное орошение</b> – глубокое одноразовое весеннее или летнее увлажнение почвы водами, как правило, местного стока.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Лункование </b>– прием обработки почвы, обеспечивающий образование лунок на ее поверхности.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Лущение</b> — обработка почвы лемешными и дисковыми лущиль&shy;никами на глубину 6—16 см, при которой происходит рыхление, частичное оборачивание и перемешивание почвы с подрезанием сорняков.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt"><span style="FONT-SIZE: 14px"><a name="10"></a>М</span><o:p></o:p></span></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt"><o:p></o:p></span></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Макроэлементы</span></b><span style="LETTER-SPACING: 0.1pt"> — азот, фосфор, калий, кальций, магний, железо, сера.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Малование</span></b><span style="LETTER-SPACING: 0.1pt"> – прием обработки почвы малой, обеспечивающий выравнивание и уплотнение верхнего слоя почвы на орошаемых участках. <o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Междурядная обработка</b> <span style="mso-spacerun: yes">&nbsp;</span>- обработка почвы между рядами растений с целью улучшения почвенных условий их жизни и уничтожения сорняков (это культивация для обработки почвы в междурядьях про&shy;пашных культур).<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Мелкая обработка почвы</b> – обработка почвы на глубину от 8 до <st1:metricconverter w:st="on" productid="16 см">16 см</st1:metricconverter>.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Микролиманы</b> – водозадерживающие емкости, образованные на поверхности поля поделкой сети замкнутых земляных валиков.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Микроэлементы</span></b><span style="LETTER-SPACING: 0.1pt"> — марга&shy;нец, цинк, медь, бор, алюминий, молибден, фтор, йод и др.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Минимальной</b> называют такую <b style="mso-bidi-font-weight: normal">обработку почвы</b>, при кото&shy;рой энергетические затраты снижают, уменьшая число и глуби&shy;ну обработок, совмещая и выполняя несколько технологических операций в одном рабочем процессе.<o:p></o:p></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Монокультура</span></b><span style="LETTER-SPACING: 0.1pt"> – бессменный посев только одной культуры в хозяй&shy;стве.<o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Мульчирование поверхности поля</span></b><span style="LETTER-SPACING: 0.1pt"> – агротехнический прием, при котором участки почвы возле растений прикрываю рыхлым слоем органического материала. Этот слой уменьшает испарение влаги, способствует повышению водоудерживающей способности почвы, устраняет опасность водной и ветровой эрозии.<o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Мульчирующая обработка почва</span></b><span style="LETTER-SPACING: 0.1pt"> – сочетание механической обработки почвы и оставление на ее поверхности измельченных растительных остатков.<o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Мульчирующий посев</span></b><span style="LETTER-SPACING: 0.1pt"> – посев по мелко обработанной почве с созданием мульчирующего слоя из стерни.<o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><span style="LETTER-SPACING: 0.1pt"><o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt"><span style="FONT-SIZE: 14px"><a name="11"></a>Н</span><o:p></o:p></span></b></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt"><o:p></o:p></span></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Нулевая обработка – </b>агротехнический прием в рамках технологии сберегающего земледелия, исключающий любое механическое вмешательство <span style="mso-spacerun: yes">&nbsp;</span>в почву перед посевом (отвальной, безотвальной), а также мелкой обработкой почвы. Н. о.,<b style="mso-bidi-font-weight: normal"> </b>при которой, почва остается не разрыхленной на протяжении всего периода после уборки до посева.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><span style="mso-bidi-font-style: italic"><span style="FONT-SIZE: 14px"><a name="12"></a>О</span><o:p></o:p></span></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><span style="mso-bidi-font-style: italic"><o:p></o:p></span></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="mso-bidi-font-style: italic">Оборачивание почвы – </span></b><span style="mso-bidi-font-style: italic">технологическая операция, обеспечивающая частичный или полный оборот обрабатываемого слоя почвы.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="mso-bidi-font-style: italic">Обработкой почвы</span></b><i> </i>называется механическое воздействие на почву рабочими органами почвообрабатывающих машин и ору&shy;дий с целью оптимизации условий жизни сельскохозяйственных растений, уничтожения сорных растений и защиты почвы от эро&shy;зии.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Обвалование почвы</b> – создание временных земляных валиков на поверхности почвы.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Обычная обработка почвы</b> – обработка почвы на глубину от 16 до <st1:metricconverter w:st="on" productid="24 см">24 см</st1:metricconverter>.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Огрех</b> – часть поля, оставшаяся необработанной (не засеянной, не убранной) после выполнения того или иного приема на поле или загоне.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Окучивание</b> – прием междурядной обработки почвы, обеспечивающий приваливание почвы к основанию стебля растений.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Основная обработка почвы</b> – <span style="mso-spacerun: yes">&nbsp;</span>первая, наиболее глубо&shy;кая обработка почвы после уборки предшественника, которая существен&shy;но изменяет сложение всего корнеобитаемого слоя почвы: вспаш&shy;ка, безотвальная обработка, фрезерование, чизелевание, специ&shy;альные приемы основной обработки почвы.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify">Отвальная обработка почвы – обработка почвы отвальными орудиями с полным или частичным оборачиванием ее слоев.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><span style="FONT-SIZE: 14px"><a name="13"></a>П</span><o:p></o:p></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><o:p></o:p></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="mso-bidi-font-size: 12.0pt">Паром</span></b><span style="mso-bidi-font-size: 12.0pt"> называется поле, свободное от возделывания сельско&shy;хозяйственных культур в течение определенного периода времени и поддерживаемое в чистом от сорняков состоянии.<o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Пахотный горизонт</span></b><span style="LETTER-SPACING: 0.1pt"> (А пах) — измененный продолжи&shy;тельной обработкой поверхностный горизонт пахотных почв, сфор&shy;мированный из гумусового или других горизонтов на глубине при по&shy;стоянной обработке почвы.<o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Перемешивание почвы</span></b><span style="LETTER-SPACING: 0.1pt"> – технологическая операция, обеспечивающая изменение взаимного расположения почвенных отдельностей с целью создания более однородного обрабатываемого слоя почвы.<o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Пестицидами </b>называют химические вещества, используемые для борьбы с вредными организмами, повреждающими сельскохозяй&shy;ственную продукцию, материалы и изделия, а также уничтожающими паразитов и переносчиков болезней сельскохозяйственных животных.<o:p></o:p></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Планировка почвы</span></b><span style="LETTER-SPACING: 0.1pt"> – выравнивание рельефа поля с образованием горизонтальной или наклонной поверхности.<o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Плантажная вспашка</span></b><span style="LETTER-SPACING: 0.1pt"> – вспашка специальным плугом на глубину более <st1:metricconverter w:st="on" productid="40 см">40 см</st1:metricconverter>.<o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Плоскорезная обработка почвы</span></b><span style="LETTER-SPACING: 0.1pt"> – безотвальная обработка почвы, плоскорежущими орудиями с сохранением большей части послеуборочных остатков на ее поверхности.<o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Плотностью сложения (объемной массой) почвы</span></b><span style="LETTER-SPACING: 0.1pt"> называют мас&shy;су 1 см<sup>3</sup> сухой почвы (высушенной до постоянной массы при тем&shy;пературе 105 °С), взятой в ее естественном (ненарушенном) сло&shy;жении. Плотность сложения минеральных почв колеблется от 0,8 до 1,8 г/см<sup>3</sup>. Для большинства сельскохозяйственных культур оптимальная плотность глинистых и суглинистых почв равна 1 —1,2 г/см<sup>3</sup>, пес&shy;чаных и супесчаных 1,2—1,4 г/см<sup>3</sup>.<o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Плотность почвы равновесная</span></b><span style="LETTER-SPACING: 0.1pt"> – плотность длительно необрабатываемой почвы.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Поверхностная обработка почву</b>, при которой почва обрабатывается различными орудиями на глубину до <st1:metricconverter w:st="on" productid="8 см">8 см</st1:metricconverter>.<o:p></o:p></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Повторная культура</span></b><span style="LETTER-SPACING: 0.1pt">, которая возделывается на одном и том же поле два года подряд.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Поглотительная способность почвы</span></b><span style="LETTER-SPACING: 0.1pt"> – способность почвы поглощать и удерживать из растворов твердые вещества и газы.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Подкормки - </b>удобрения<b style="mso-bidi-font-weight: normal">,</b> вносимые в период вегетации растений.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><span style="LETTER-SPACING: 0.1pt">Под<i style="mso-bidi-font-style: normal"> </i><b style="mso-bidi-font-weight: normal">структурой почвы</b> понимают различные по величине и форме почвенные агрегаты, в которые склеены почвенные частицы. <o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="mso-bidi-font-size: 12.0pt">Полупаровая обработка почвы – </span></b><span style="mso-bidi-font-size: 12.0pt">совокупность приемов сплошной обработки почвы после раноубираемых непаровых культур, выполняемых в летне-осенний период, состоит из серии послойных обработок, аналогичных обработкам почвы в полях чистого пара.<o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Пористость, или скважность,</span></b><span style="LETTER-SPACING: 0.1pt"> — суммарный объем всех пор и промежутков между твердыми частичками и комочками почвы в единице ее объема в ненарушенном состоянии. Опти&shy;мальная пористость для большинства сельскохозяйственных рас&shy;тений 50—60 %. <o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Посевные качества семян</span></b><span style="LETTER-SPACING: 0.1pt"> – совокупность свойств семян, характеризующих их пригодность для посева. Относятся энергия прорастания, всхожесть, жизнеспособность, масса 1000 семян, чистота, влажность и др.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.05pt">Послепосевная обработка почвы – </span></b><span style="LETTER-SPACING: 0.05pt">обработка почвы, проводимая после посева или посадки с.-х. культур<b style="mso-bidi-font-weight: normal">. <o:p></o:p></b></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Почва</b> – поверхностный слой земной коры, который возникает в результате воздействия воды, воздуха и различного рода организмов на литосферу и обладает плодородием. <o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Почвенный профиль</span></b><span style="LETTER-SPACING: 0.1pt"> – <i style="mso-bidi-font-style: normal"><span style="mso-spacerun: yes">&nbsp;</span></i>совокупность генетических горизонтов, образовавшихся в результате почвообразователь&shy;ного процесса, характеризующийся определен&shy;ной сменой горизонтов в вертикальном направлении.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Предпосевная обработка почвы</span></b><span style="LETTER-SPACING: 0.1pt"> – обработка почвы, выполняемая перед посевом или посадкой с.-х. культур.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="mso-bidi-font-size: 12.0pt">Предшественник</span></b><span style="mso-bidi-font-size: 12.0pt"> — сельскохозяй&shy;ственная культуру или пар, занимавшие данное поле в предыду&shy;щем году.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="mso-bidi-font-size: 12.0pt">Прием обработки почвы</span></b><span style="mso-bidi-font-size: 12.0pt"> – однократное воздействие на почву рабочими органами почвообрабатывающих машин и орудий с целью выполнения одной или нескольких технологических операций.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Прикатывание</b> <span style="mso-spacerun: yes">&nbsp;</span>- прием обработки почвы катками, обеспечивающий ее уплотнение, крошение и частичное вы&shy;равнивание поверхности поля.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="mso-bidi-font-size: 12.0pt">Промежуточные культуры</span></b><span style="mso-bidi-font-size: 12.0pt">, ко&shy;торые выращивают в период времени, когда пашня свободна от возделывания основных культур севооборота. В зависимости от сроков сева и места в севообороте промежуточные культуры делят на ози&shy;мые, пожнивные, поукосные и подсевные.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Пропашные культуры</b> – с.-х. растения, для нормального роста и развития которых необходимы большие площади питания (междурядья 45-<st1:metricconverter w:st="on" productid="90 см">90 см</st1:metricconverter>) и междурядная обработка почвы.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="mso-bidi-font-size: 12.0pt">Противоэрозионная обработка почвы</span></b><span style="mso-bidi-font-size: 12.0pt"> – обработка почвы направленная на защиту ее от эрозии.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="mso-bidi-font-size: 12.0pt">Прямой посев</span></b><span style="mso-bidi-font-size: 12.0pt"> – посев по необработанному полю по стерне и равномерно разбросанной измельченной соломе.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><span style="mso-bidi-font-size: 12.0pt"><o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><span style="mso-bidi-font-size: 12.0pt"><span style="FONT-SIZE: 14px"><a name="14"></a>Р</span><o:p></o:p></span></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><span style="mso-bidi-font-size: 12.0pt"><o:p></o:p></span></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Равномерность глубины обработки почвы – </span></b><span style="LETTER-SPACING: 0.1pt">допустимые отклонения фактической глубины обработки почвы от заданной.<b style="mso-bidi-font-weight: normal"> <o:p></o:p></b></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Развальная борозда – </span></b><span style="LETTER-SPACING: 0.1pt">углубления, образующиеся при отваливании пластов почвы друг от друга при встречных (смежных) проходах агрегата.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Реакция почвенного раствора </span></b>определяется величиной обратного логарифма концентрации водородных ионов (рН) в почвенном растворе. При рН 4 почва считается очень кислой (встречается редко), при рН 5 — сильнокислой, рН 6 — слабокислой, рН 7 — нейтральной, рН 8 — щелочной, рН 9 — сильнощелочной (встречается редко.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><span class="FontStyle44"><b style="mso-bidi-font-weight: normal"><span style="FONT-STYLE: normal; mso-bidi-font-style: italic">Регуляторы роста и развития растений</span></b></span><span class="FontStyle44" style="FONT-STYLE: normal; mso-bidi-font-style: italic"> — </span><span class="FontStyle33">группа химических веществ, влияющих на процессы роста и развития растений.</span><o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Ретарданты</b> – химические средства для торможения роста растений.<o:p></o:p></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Ротация</span></b><span style="LETTER-SPACING: 0.1pt"> — период времени, в течение которого все культуры проходят через каждое поле севооборота в последовательности, предусмотренной схемой севооборота.<o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Рыхление почвы</span></b><span style="LETTER-SPACING: 0.1pt"> – технологическая операция, обеспечивающая изменение взаимного расположения почвенных отдельностей с увеличением объема пор.<o:p></o:p></span></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center">&nbsp;</p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt"><span style="FONT-SIZE: 14px"><a name="15"></a>С</span><o:p></o:p></span></b></p>
    <p class="MsoNormal" style="BACKGROUND: white; MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt"><o:p></o:p></span></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Свальный гребень – </b>гребень, образующийся от приваливания пластов почвы друг к другу при встречных (смежных) проходах агрегата.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Севооборотом</b> называется научно обоснованное чередование культур и паров во времени и по полям.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Сидераты (зеленые удобрения)</b>— свежая растительная масса, которую запа&shy;хивают в почву для обогащения ее и последующих культур органическим веществом и элементами питания.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Система обработки почвы</b> — это совокупность последовательно выполняемых приемов обработки почвы при возделывании опре&shy;деленных культур. По времени выполнения системы обработки почвы делятся на зяблевую обработку, предпосевную и послепосевную. Осеннюю вспашку почвы под яровые культуры называют <b style="mso-bidi-font-weight: normal">зябле&shy;вой</b>, весеннюю — весенней вспашкой. <o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Система удобрения</b> — это основанное на знаниях свойств и взаи&shy;моотношений растений, почв и удобрений агрономически и эконо&shy;мически наиболее эффективное и экологически безопасное приме&shy;нение удобрений в каждом севообороте и внесевооборотном участ&shy;ке с учетом конкретных климатических и экономических условий.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Сорняками</span></b><span style="LETTER-SPACING: 0.1pt"> называются растения, не возделываемые человеком, но засоряющие сельскохозяйственные угодья.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Сорт</span></b><span style="LETTER-SPACING: 0.1pt"> – совокупность более или менее сходных по хозяйственно-биологическим свойствам и морфологическим признакам растений одной культуры, родственных по происхождению, приспособленных к определенным условиям произрастания.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Специализированными сорняками</span></b><span style="LETTER-SPACING: 0.1pt"> принято называть растения, засоряющие посевы родственных культур.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Стерня</span></b><span style="LETTER-SPACING: 0.1pt"> – нижняя часть стеблей зерновых культур, оставшаяся на корню после уборки урожая. Способствует задержанию снега и накоплению влаги, препятствуя водной и ветровой эрозии.</span><o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><span style="LETTER-SPACING: 0.1pt">Под<i style="mso-bidi-font-style: normal"> </i><b style="mso-bidi-font-weight: normal">структурой почвы</b> понимают различные по величине и форме почвенные агрегаты, в которые склеены почвенные частицы. <o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Структурность</span></b><span style="LETTER-SPACING: 0.1pt"> –<span style="mso-spacerun: yes">&nbsp; </span>способность почвы распадаться на отдельные агрегаты.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Ступенчатая вспашка</span></b><span style="LETTER-SPACING: 0.1pt"> – вспашка, обеспечивающая ступенчатый профиль дна борозды.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><span style="LETTER-SPACING: 0.1pt">Сушка семян – удаление из них такого количества влаги, после которого он могут продолжительное время хранится не снижая посевных качеств.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><span style="LETTER-SPACING: 0.1pt"><o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt"><span style="FONT-SIZE: 14px"><a name="16"></a>Т</span><o:p></o:p></span></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt"><o:p></o:p></span></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Террасирование почвы – </span></b><span style="LETTER-SPACING: 0.1pt">создание на крутых склонах выровненных ступеней для возделывания с.-х. культур и уменьшение эрозии почвы.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Теплоемкость</span></b><span style="LETTER-SPACING: 0.1pt"> — способность почвы поглощать и удерживать теплоту. Она измеряется количеством теплоты (Дж), которое необходимо для нагревания <st1:metricconverter w:st="on" productid="1 г">1 г</st1:metricconverter> почвы (весовая теплоемкость) или 1 см<sup>3</sup> почвы (объемная теплоемкость) на 1°.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Теплоизлучение</span></b><i style="mso-bidi-font-style: normal"><span style="LETTER-SPACING: 0.1pt"> – </span></i><span style="LETTER-SPACING: 0.1pt"><span style="mso-spacerun: yes">&nbsp;</span>это по&shy;теря или отдача энергии в окружающую атмосферу.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Теплопоглощение</span></b><span style="LETTER-SPACING: 0.1pt"> — способность почвы поглощать тепловые лучи Солнца.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Теплопроводность</span></b><span style="LETTER-SPACING: 0.1pt"> — это способность почвы передать тепло&shy;вую энергию от более нагретых слоев к более холодным. Она из&shy;меряется количеством теплоты (Дж), которое проходит в 1 с че&shy;рез 1 см<sup>2</sup> почвы толщиной <st1:metricconverter w:st="on" productid="1 см">1 см</st1:metricconverter> при разности температур в 1°С.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Технические культуры</b> – возделываемые растения, которые используют как сырьё для различных отраслей промышленности (лен, подсолнечник, картофель, мята и др.).<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Травмирование семян</b> – их механическое повреждение, вызываемое рабочими органами машин при уборке и доработке семян, а также повреждение грызунами, микроорганизмами.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Транспирационный коэффициент</span></b><span style="LETTER-SPACING: 0.1pt"> — количество единиц воды, которое расходуется растением на создание единицы сухого органическо&shy;го вещества.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt">Трехъярусная вспашка</span></b><span style="LETTER-SPACING: 0.1pt"> – обработка почвы, обеспечивающая частичное или полное перемещение трех слоев (горизонтов), их крошение и рыхление.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><span style="LETTER-SPACING: 0.1pt"><span style="FONT-SIZE: 14px"><a name="17"></a>У</span><o:p></o:p></span></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Углубление пахотного слоя – </b>увеличение глубины пахотного слоя за счет нижележащих слоев или горизонтов при обработке почвы.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Удобрения</b> – вещества, предназначенные для улучшения питания растений и повышения плодородия почв в целях увеличения урожая сельскохозяйственных растений и улуч&shy;шения качества получаемой продукции.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Уплотнение почвы</b> – технологическая операция, обеспечивающая изменение взаимного расположения почвенных отдельностей с уменьшением объема пор.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><span style="FONT-SIZE: 14px"><a name="18"></a>Ф</span><o:p></o:p></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><o:p></o:p></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Фрезерование</b> — обработка почвы фрезой на глубину до <st1:metricconverter w:st="on" productid="20 см">20 см</st1:metricconverter>, обеспечивающая ее интенсивное рыхление, тщательное перемеши&shy;вание и уничтожение сорняков.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Фумиганты</b> - вещества, применяемые в паро- и газообразном со&shy;стоянии для уничтожения вредителей и возбудителей болезней.<o:p></o:p></p>
    <p class="Style12" style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 0cm; LINE-HEIGHT: normal; mso-pagination: widow-orphan"><span class="FontStyle44"><b style="mso-bidi-font-weight: normal"><span style="FONT-STYLE: normal; mso-bidi-font-style: italic">Фунгициды</span></b></span><span class="FontStyle44"><em> — </em></span><span class="FontStyle33">химические препараты для защиты сельскохозяй&shy;ственных культур от патогенных грибов и бактерий — возбудите&shy;лей болезней растений.<o:p></o:p></span></p>
    <p class="Style12" style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 0cm; LINE-HEIGHT: normal; mso-pagination: widow-orphan"><span class="FontStyle33"><o:p></o:p></span></p>
    <p class="Style12" style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 0cm; LINE-HEIGHT: normal; TEXT-ALIGN: center; mso-pagination: widow-orphan" align="center"><span class="FontStyle33"><b style="mso-bidi-font-weight: normal"><span style="FONT-SIZE: 14px"><a name="19"></a>Х</span><o:p></o:p></b></span></p>
    <p class="Style12" style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 0cm; LINE-HEIGHT: normal; TEXT-ALIGN: center; mso-pagination: widow-orphan" align="center"><span class="FontStyle33"><b style="mso-bidi-font-weight: normal"><o:p></o:p></b></span></p>
    <p class="Style12" style="MARGIN: 0cm 0cm 0pt; TEXT-INDENT: 0cm; LINE-HEIGHT: normal; mso-pagination: widow-orphan"><span class="FontStyle33"><b style="mso-bidi-font-weight: normal">Хранение семян</b></span><span class="FontStyle33"> – комплекс мероприятий, способствующих сохранению кондиционного уровня качества семян и сведению к минимуму их потерь.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center">&nbsp;</p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><span style="FONT-SIZE: 14px"><a name="20"></a>Ч</span><o:p></o:p></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><o:p></o:p></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Чизелевание</b> — прием безотвальной обработки почвы чизельными орудиями, обеспечивающая ее рыхление на глубину 20 — <st1:metricconverter w:st="on" productid="40 см">40 см</st1:metricconverter> при частичном перемешивании.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Чистота семян</b> – содержание семян основной культуры в исследуемом образце, выраженное в процентах к общему количеству семян.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal"><span style="mso-bidi-font-size: 12.0pt">Чистым паром</span></b><span style="mso-bidi-font-size: 12.0pt"> называется поле, сво&shy;бодное от возделываемых сельскохозяйственных культур и обра&shy;батываемое в течение всего вегетационного периода. Чистые пары могут быть черными и ранними. <b style="mso-bidi-font-weight: normal">Черным</b> называ&shy;ется чистый пар, основная обработка которого проводится летом или осенью предшествующего парованию года, <b style="mso-bidi-font-weight: normal">ранним</b> — обра&shy;ботка которого начинается весной в год парования.<o:p></o:p></span></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center">&nbsp;</p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><span style="mso-bidi-font-size: 12.0pt"><span style="FONT-SIZE: 14px"><a name="21"></a>Ш</span><o:p></o:p></span></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><span style="mso-bidi-font-size: 12.0pt"><o:p></o:p></span></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Шлейфование</b> — прием обработки почвы шлейфом, обеспечивающий выравнивание ее поверхности и частичное рыхление верхнего слоя, что снижает испарение влаги из почвы.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center">&nbsp;</p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><span style="FONT-SIZE: 14px"><a name="22"></a>Щ</span><o:p></o:p></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><b style="mso-bidi-font-weight: normal"><o:p></o:p></b></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Щелевание – </b>прием обработки почвы щелевателями, обеспечивающий глубокое ее подрезание с целью повышения водопроницаемости.<o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center">&nbsp;</p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><span style="FONT-SIZE: 14px"><b><a name="23"></a>Э</b></span><o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: center" align="center"><o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><b style="mso-bidi-font-weight: normal">Энергия прорастания </b><span style="mso-spacerun: yes">&nbsp;</span>- способность семян к дружному прорастанию, определяется процентом нормально проросших семян за определенное время.<o:p></o:p></p></span>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><span style="COLOR: #000000"><span style="FONT-SIZE: 12px"><b style="mso-bidi-font-weight: normal">Эрозия почвы</b> – <span style="mso-spacerun: yes">&nbsp;</span>процессы разрушения ее поверхностного слоя под действием ветра (ветровая) или воды (водная). Водную эрозию, возникающую в орошаемом земледелии, на&shy;зывают <b style="mso-bidi-font-weight: normal">ирригационной</b>, ветровую эрозию — <b style="mso-bidi-font-weight: normal">дефляцией</b>.</span></span><o:p></o:p></p>
    <p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt; TEXT-ALIGN: justify"><o:p></o:p></p>
</div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
